<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mentorpi_description</name>
  <version>0.1.0</version>
  <description>MentorPi 巡检小车 + UR3e 机械臂 URDF 描述(仿真用)</description>
  <maintainer email="wh@todo.todo">wh</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>urdf</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>gazebo_ros_pkgs</exec_depend>
  <exec_depend>gazebo_ros2_control</exec_depend>
  <exec_depend>Universal_Robots_ROS2_Description</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
